### ISSUE TITLE
Create app boillerplate

### ISSUE THREAD

**Issue by Codykilpatrick** [Codykilpatrick/Celestia#2]
We need to fill out the app packages. I'd like to use React/Typescript with Yarn as our package manager  but am open to ideas.

**Comment by Codykilpatrick** [comment]
Looking at a starting point for our front end:
https://www.radix-ui.com/themes/docs/overview/getting-started

Maybe using Radix themes? Curious what you guys think.

**Comment by mjlueder** [comment]
Radix looks cool and feels decently in-line with the what I've seen of the game. I'm in.

Honestly most of what I've done so far has been through templates like GA had, so I've never had to set up packages etc on my own. And I've never used yarn. I'm all about learning new things, so I'd like to, but I also feel pretty useless at the moment in terms of being able to jump in and help!

**Comment by Codykilpatrick** [comment]
For sure! So first thing is yarn functions pretty similar to how we used NPM in GA. If you go to the package.json you'll see a section called "scripts". Those are all able to run with `yarn script`. First thing though is doing `yarn install` just like `npm install` it installs all of your packages.

For example: 
`yarn start` launches the app in developer mode so you can go to "localhost:300" and see it running
`yarn lint` runs a check on all the code to make sure there are no Typescript errors and will let you know in the command line if there are.

As far as adding new packages:
its similar to doing it with npm but you will do `yarn add packagename`.
One thing to note is each package that we have will have its own "package.json" so when installing a package for the app make sure you are in there in the command line or it wont work!

If you wanted to rock with the Radix UI, their getting started with themes section seems good!
https://www.radix-ui.com/themes/docs/overview/getting-started

I also imagine once the theme is setup you can use their "primatives" Which are basically little component templates:
https://www.radix-ui.com/primitives/docs/guides/styling

Or the icons on their website too!
